include ../makefiles/Makefile.inc

FILES = \
	README.html\
	Greeting.idl\
	GreetingImpl.C\
	GreetingImpl.h\
	setup.xml

REL_DIR = corba/hello-tie

all:
	$(MKDIR) $(TGT_DIR)
	$(CP) $(FILES) $(TGT_DIR)
	$(call INSTALL_REPL_MAIN,server.C)
	$(call INSTALL_REPL_MAIN,client.C)
	$(call INSTALL_MK_FILE)
