
EXAMPLES = bigbank-ws hello-ocsa bigbank-ocsa calculator-ocsa hello-ws

FILES = Makefile stdmk

all:
	@if [ ! -d $(POCOCAPSULE_DIR)/install/examples/web-services ]; then \
	  mkdir -p $(POCOCAPSULE_DIR)/install/examples/web-services; \
	fi;
	cp $(FILES) $(POCOCAPSULE_DIR)/install/examples/web-services
	@for ex_dir in $(EXAMPLES); do \
	  $(MAKE) -C $$ex_dir -f makefiles/Makefile.install; \
	done;
