vb:
	@echo "-------------------------------------------------------------------"
	@echo "  Building a simple demo DDS for this example"
	@echo "-------------------------------------------------------------------"
	cd pocodds 
	$(MAKE) -f makefiles/Makefile.vbWindows_NT all
	cd ..
	@echo "-------------------------------------------------------------------"
	@echo "  Building this example"
	@echo "-------------------------------------------------------------------"
	$(MAKE) -f makefiles/Makefile.vbWindows_NT all

tao:
	@echo "-------------------------------------------------------------------"
	@echo "  Building a simple demo DDS for this example"
	@echo "-------------------------------------------------------------------"
	cd pocodds
	$(MAKE) -f makefiles/Makefile.taoWindows_NT all
	cd ..
	@echo "-------------------------------------------------------------------"
	@echo "  Building this example"
	@echo "-------------------------------------------------------------------"
	$(MAKE) -f makefiles/Makefile.taoWindows_NT all

clean_vb:
	cd pocodds
	$(MAKE) -f makefiles/Makefile.vbWindows_NT clean
	cd ..
	$(MAKE) -f makefiles/Makefile.vbWindows_NT clean

clean_tao:
	cd pocodds
	$(MAKE) -f makefiles/Makefile.taoWindows_NT clean
	cd ..
	$(MAKE) -f makefiles/Makefile.taoWindows_NT clean

clean: clean_vb clean_tao
