vb:
	@echo "-------------------------------------------------------------------"
	@echo "  Building a simple demo DDS for this example"
	@echo "-------------------------------------------------------------------"
	cd pocodds; $(MAKE) -f makefiles/Makefile.vb all; cd ..
	@echo "-------------------------------------------------------------------"
	@echo "  Building this example"
	@echo "-------------------------------------------------------------------"
	$(MAKE) -f makefiles/Makefile.vb all

tao:
	@echo "-------------------------------------------------------------------"
	@echo "  Building a simple demo DDS for this example"
	@echo "-------------------------------------------------------------------"
	cd pocodds; $(MAKE) -f makefiles/Makefile.tao all; cd ..
	@echo "-------------------------------------------------------------------"
	@echo "  Building this example"
	@echo "-------------------------------------------------------------------"
	$(MAKE) -f makefiles/Makefile.tao all

clean_vb:
	cd pocodds; $(MAKE) -f makefiles/Makefile.vb clean; cd ..
	$(MAKE) -f makefiles/Makefile.vb clean

clean_tao:
	cd pocodds; $(MAKE) -f makefiles/Makefile.tao clean; cd ..
	$(MAKE) -f makefiles/Makefile.tao clean

clean: clean_vb clean_tao
