module RTC {
	typedef long ReturnCode_t;

	local interface LifeCycle {
		ReturnCode_t initialize();
		ReturnCode_t finalize();

		// other operations omitted
	};

	local interface ComponentAction {
		// all operations omitted
	};

	local interface LightweightRTObject : LifeCycle, ComponentAction {
		string	name(); // for illustration purpose
	};
};
