include $(POCOCAPSULE_DIR)/examples/web-services/makefiles/Makefile.inc

FILES = README.html Makefile server.config service.composite \
        setup.xml config.xml Hello.wsdl client.C server.C \
        MyHelloServiceImpl.h 

REL_DIR = web-services/hello-ocsa

all:
	$(MKDIR) $(TGT_DIR)
	$(CP) $(FILES) $(TGT_DIR)

