include ../stdmk

FILES = \
	main$(LIB_SUFFIX) \
	TickGenImpl$(LIB_SUFFIX) \
	GPSLocatorImpl$(LIB_SUFFIX) \
	NavDisplayImpl$(LIB_SUFFIX) \
	reflx$(LIB_SUFFIX) \
	setup.ctx

exe: $(FILES)

all: exe 

setup_reflx.cc: setup.xml
	$(POCO_PROJ) -s=_reflx.cc -h=GPSLocatorImpl.h -h=NavDisplayImpl.h \
	-h=TickGenImpl.h setup.xml

reflx$(LIB_SUFFIX): setup_reflx$(LIB_SUFFIX)
	mv setup_reflx$(LIB_SUFFIX) reflx$(LIB_SUFFIX)

clean:
	$(RM) *.o *.cc $(FILES)
