include $(POCOCAPSULE_DIR)/examples/basic-ioc/stdmkdir/stdmk

all: 
	$(CC) $(LIB_CREATION_FLAG) -g AudioEffect.C -o AudioEffect.so
	$(CC) $(LIB_CREATION_FLAG) -g FMTransmitterReceiver.C -o FMTransmitterReceiver.so
	$(POCO_PROJ) -s=_reflx.cc -h=AudioEffect.h -h=FMTransmitterReceiver.h setup.xml
	$(CC) $(LIB_CREATION_FLAG) $(POCO_LIBPATH) $(LIBPOCO) \
				-g setup_reflx.cc -o reflx.so
	$(CC) main.C $(POCO_LIBPATH) $(LIBPOCO) $(LIBPOCOXML) -o main

clean:
	rm -rf *.o *_reflx.* *.so main
