include $(POCOCAPSULE_DIR)/examples/web-services/makefiles/Makefile.inc

FILES = README.html config.xml setup.xml Makefile \
        AccountService.wsdl StockQuoteWebService.wsdl \
        Components.C Components.h bigbank-ocsa.jpg server.C client.C \
        bigbank.account.composite server.config

REL_DIR = web-services/bigbank-ocsa

all:
	$(MKDIR) $(TGT_DIR)
	$(CP) $(FILES) $(TGT_DIR)

