include ../makefiles/Makefile.inc

FILES = README.html foo.h foo.C setup.xml

REL_DIR = basic-ioc/on-error

all:
	$(MKDIR) $(TGT_DIR)
	$(CP) $(FILES) $(TGT_DIR)
	$(call INSTALL_MAIN)
	$(call INSTALL_MK_FILE)

