include ../stdmkdir/stdmk.win

all: main.exe foo$(DLL_SUFFIX) reflx$(DLL_SUFFIX)

setup_reflx.cc: setup.xml
	$(POCO_PROJ) -s=_reflx.cc -h=foo.h -H=stdio.h -H=iostream setup.xml

reflx$(DLL_SUFFIX): setup_reflx.obj
	$(LINK_DLL) /OUT:$@ setup_reflx.obj \
	$(POCO_LIBPATH) $(LIBPOCO) foo$(LIB_SUFFIX)

foo.obj: foo.C
	$(CC) $(CCFLAGS) /DBUILD_DLL /c /Tp foo.C 

foo$(DLL_SUFFIX): foo.obj
	$(LINK_DLL) /OUT:$@ foo.obj 

main.exe: main.obj
	$(LINK_EXE) /OUT:$@ main.obj $(POCO_LIBPATH) $(LIBPOCO) $(LIBPOCOXML)

clean:
	del *.obj *.pdb *.lib *.exe *.dll *.exp *.cc *.exp *.ilk *.manifest
