//
// minimum CF enough for this example
//
module CF {
	// 
	// a base for application port, for printing out the connection end point
	//
	interface Base {
		readonly attribute string	name;
	};
	
	interface Resource : Base {
		Object	getPort(in string key);
	};

	interface Port : Base {
		void connectPort(in Object provider, in string conn_id);
		void disconnectPort(in string conn_id);
	};
};
