include $(POCOCAPSULE_DIR)/examples/basic-ioc/stdmkdir/stdmk

EXE = main reflx.so RangeScannerComponent.so ServoComponent.so \
		VehicleController.so BumperSensorComponent.so

all: $(EXE)

main: main.C
	$(CC) $(CCFLAGS) -o $@ $< $(LIBPATH) $(LIBORB) \
				$(POCO_LIBPATH) $(LIBPOCO) 

reflx.so: setup.xml
	$(POCO_PROJ) -s=_reflx.cc -h=objImpls.h -h=VehicleController.h \
			-h=RangeScannerComponent.h -h=ServoComponent.h \
			-h=BumperSensorComponent.h setup.xml
	$(CC) $(LIB_CREATION_FLAG) -o $@ setup_reflx.cc  $(POCO_LIBPATH) $(LIBPOCO) 

RangeScannerComponent.so: RangeScannerComponent.C 
	$(CC) $(LIB_CREATION_FLAG) -o $@ RangeScannerComponent.C 

ServoComponent.so: ServoComponent.C 
	$(CC) $(LIB_CREATION_FLAG) -o $@ ServoComponent.C

BumperSensorComponent.so: BumperSensorComponent.C 
	$(CC) $(LIB_CREATION_FLAG) -o $@ BumperSensorComponent.C

VehicleController.so: VehicleController.C 
	$(CC) $(LIB_CREATION_FLAG) -o $@ VehicleController.C

clean:
	-rm -f core *.o *.so *.hh *.cc *_reflx.* main
