include ../makefiles/Makefile.inc

FILES = \
	README.html\
	Interfaces.idl\
	GPSLocatorImpl.C\
	GPSLocatorImpl.h\
	TickGenImpl.C\
	TickGenImpl.h\
	NavDisplayImpl.h\
	NavDisplayImpl.C\
	gps.jpg\
	setup.xml

REL_DIR = corba/gps

all:
	$(MKDIR) $(TGT_DIR)
	$(CP) $(FILES) $(TGT_DIR)
	$(call INSTALL_REPL_MAIN,main.C)
	$(call INSTALL_MK_FILE)
