include ../stdmk.vb

FILES = CF_c.cc CF_s.cc sample_c.cc sample_s.cc \
        main.so reflx.so scahelper.so sampleImpl.so setup.ctx

all: $(FILES)

setup_reflx.cc: setup.xml
	$(POCO_PROJ) -s=_reflx.cc -h=scahelper.h -h=sampleImpl.h $<

scahelper.so: scahelper.o CF_s.o CF_c.o
	$(LINK_SLIB)

sampleImpl.so: sampleImpl.o sample_c.o sample_s.o
	$(LINK_SLIB)

reflx$(LIB_SUFFIX): setup_reflx$(LIB_SUFFIX)
	mv setup_reflx$(LIB_SUFFIX) reflx$(LIB_SUFFIX)

clean:
	$(RM) *.o *.hh $(EXE)

