include $(POCOCAPSULE_DIR)/examples/web-services/makefiles/Makefile.inc

FILES = README.html config.xml setup.xml Makefile \
        AccountService.wsdl StockQuoteWebService.wsdl \
        Components.C Components.h bigbank.gif server.C client.C

REL_DIR = web-services/bigbank-ws

all:
	$(MKDIR) $(TGT_DIR)
	$(CP) $(FILES) $(TGT_DIR)

