include ../makefiles/Makefile.inc

FILES = \
	README.html\
	EmitterImpl.C\
	EmitterImpl.h\
	ListenerImpl.C\
	ListenerImpl.h\
	MyTypedEvent.idl\
	publish.xml\
	subscribe.xml

REL_DIR = corba/event-classic

all:
	$(MKDIR) $(TGT_DIR)
	$(CP) $(FILES) $(TGT_DIR)
	$(call INSTALL_MK_FILE)
	$(call INSTALL_REPL_MAIN,publisher.C)
	$(call INSTALL_REPL_MAIN,subscriber.C)
