all:
	@echo 
	@echo "*********** hello web services example ****************"
	cd hello-ws; make all; cd ..;

	@echo
	@echo "*********** hello oasis-ocsa component example ********"
	cd hello-ocsa; make all; cd ..;

	@echo
	@echo "*********** bigbank web service example ***************"
	cd bigbank-ws; make all; cd ..;

	@echo
	@echo "*********** bigbank oasis-ocsa component example ******"
	cd bigbank-ocsa; make all; cd ..;

	@echo
	@echo "*********** calculator oasis-ocsa component example ***"
	cd calculator-ocsa; make all; cd ..;


clean:
	cd hello-ws; make clean; cd ..;
	cd hello-ocsa; make clean; cd ..;
	cd bigbank-ws; make clean; cd ..;
	cd bigbank-ocsa; make clean; cd ..;
	cd calculator-ocsa; make clean; cd ..;
