include ../stdmkdir/stdmk.win

APP_DLLS =  RangeScannerComponent$(DLL_SUFFIX) ServoComponent$(DLL_SUFFIX) \
	VehicleController$(DLL_SUFFIX) BumperSensorComponent$(DLL_SUFFIX) 

APP_LIBS =  RangeScannerComponent$(LIB_SUFFIX) ServoComponent$(LIB_SUFFIX) \
	VehicleController$(LIB_SUFFIX) BumperSensorComponent$(LIB_SUFFIX) 

EXE = main.exe $(APP_DLLS) reflx$(DLL_SUFFIX)

all: $(EXE)

RangeScannerComponent.obj: RangeScannerComponent.C
	$(CC) $(CCFLAGS) /DBUILD_DLL /c /Tp RangeScannerComponent.C

RangeScannerComponent$(DLL_SUFFIX): RangeScannerComponent.obj 
	$(LINK_DLL) $(DLL_LD_FLAGS) /OUT:$@ \
	RangeScannerComponent.obj 
 
ServoComponent.obj: ServoComponent.C
	$(CC) $(CCFLAGS) /DBUILD_DLL /c /Tp ServoComponent.C

ServoComponent$(DLL_SUFFIX): ServoComponent.obj
	$(LINK_DLL) $(DLL_LD_FLAGS) /OUT:$@ \
	ServoComponent.obj 

VehicleController.obj: VehicleController.C
	$(CC) $(CCFLAGS) /DBUILD_DLL /c /Tp VehicleController.C

VehicleController$(DLL_SUFFIX): VehicleController.obj 
	$(LINK_DLL) $(DLL_LD_FLAGS) /OUT:$@ \
	VehicleController.obj

BumperSensorComponent.obj: BumperSensorComponent.C
	$(CC) $(CCFLAGS) /DBUILD_DLL /c /Tp BumperSensorComponent.C

BumperSensorComponent$(DLL_SUFFIX): BumperSensorComponent.obj
	$(LINK_DLL) $(DLL_LD_FLAGS) /OUT:$@ \
	BumperSensorComponent.obj

setup_reflx.cc: setup.xml
	$(POCO_PROJ) -s=_reflx.cc -h=objImpls.h -h=VehicleController.h \
				-h=RangeScannerComponent.h -h=ServoComponent.h \
				-h=BumperSensorComponent.h setup.xml

setup_reflx.obj: setup_reflx.cc
	$(CC) $(CCFLAGS) $(POCO_IMPORT) /c /Tp setup_reflx.cc

reflx$(DLL_SUFFIX): setup_reflx.obj 
	$(LINK_DLL) $(DLL_LD_FLAGS) /OUT:$@ setup_reflx.obj \
	$(POCO_LIBPATH) $(LIBPOCO) $(ORB_LIBPATH) $(LIBORB) $(APP_LIBS) 

main.exe: main.obj
	$(LINK_EXE) /OUT:$@ main.obj $(POCO_LIBPATH) $(LIBPOCO)

clean:
	del *.obj *.pdb *.lib *.exe *.dll *.exp *.cc *.exp *.ilk *.manifest
