include ../stdmkdir/stdmk.win

all: main.exe TickGenImpl$(DLL_SUFFIX) \
     GPSLocatorImpl$(DLL_SUFFIX) NavDisplayImpl$(DLL_SUFFIX) \
     reflx$(DLL_SUFFIX)

setup_reflx.cc: setup.xml
	$(POCO_PROJ) -s=_reflx.cc -h=GPSLocatorImpl.h -h=NavDisplayImpl.h -h=TickGenImpl.h setup.xml

reflx$(DLL_SUFFIX): setup_reflx.obj
	$(LINK_DLL) /OUT:$@ setup_reflx.obj \
	$(POCO_LIBPATH) $(LIBPOCO) TickGenImpl$(LIB_SUFFIX) \
        GPSLocatorImpl$(LIB_SUFFIX) NavDisplayImpl$(LIB_SUFFIX)

TickGenImpl.obj: TickGenImpl.C
	$(CC) $(CCFLAGS) /DBUILD_DLL /c /Tp TickGenImpl.C

GPSLocatorImpl.obj: GPSLocatorImpl.C
	$(CC) $(CCFLAGS) /DBUILD_DLL /c /Tp GPSLocatorImpl.C

NavDisplayImpl.obj: NavDisplayImpl.C
	$(CC) $(CCFLAGS) /DBUILD_DLL /c /Tp NavDisplayImpl.C

TickGenImpl$(DLL_SUFFIX): TickGenImpl.obj
	$(LINK_DLL) /OUT:$@ TickGenImpl.obj $(POCO_LIBPATH) $(LIBPOCO)

GPSLocatorImpl$(DLL_SUFFIX): GPSLocatorImpl.obj
	$(LINK_DLL) /OUT:$@ GPSLocatorImpl.obj $(POCO_LIBPATH) $(LIBPOCO)

NavDisplayImpl$(DLL_SUFFIX): NavDisplayImpl.obj
	$(LINK_DLL) /OUT:$@ NavDisplayImpl.obj $(POCO_LIBPATH) $(LIBPOCO)

main.exe: main.obj
	$(LINK_EXE) /Out:$@ main.obj \
	$(POCO_LIBPATH) $(LIBPOCO) $(LIBPOCOXML)

clean:
	del *.obj *.pdb *.lib *.exe *.dll *.exp *.cc *.exp *.ilk *.manifest
