module sample 
{
  struct NewsBrief 
  {
    string subject;
    string message;
  };

  interface MyTypedEvent 
  {
    // event operations
    void hello(in string greeting, in string sender);
    void headlinenews(in NewsBrief news, in string sender);
    void stockquote(in string stock_id, in float price);
  };
};
