include ../stdmk

FILES = \
	main$(LIB_SUFFIX) \
	TickGenImpl$(LIB_SUFFIX) \
	GPSLocatorImpl$(LIB_SUFFIX) \
	NavDisplayImpl$(LIB_SUFFIX) \
	reflx$(LIB_SUFFIX) \
	setup.ctx

exe: $(FILES)

all: exe 

setup.ctx: setup.xml
	$(POCO_ENCODE) -s=.ctx setup.xml

setup_reflx.cc: setup.xml
	$(POCO_PROJ) -s=_reflx.cc -h=GPSLocatorImpl.h -h=NavDisplayImpl.h -h=TickGenImpl.h setup.xml

%$(LIB_SUFFIX):%.o
	$(LD) $(LD_PARTIAL_FLAGS) -o $@.tmp $^
	$(NM) -g $@.tmp | $(MUNCH) > ctdt.c
	$(CC) -g -fdollars-in-identifiers -ansi $(CFLAGS) -c ctdt.c
	$(LD) $(LD_PARTIAL_FLAGS) -o $@ $@.tmp ctdt.o
	-$(RM) *.tmp ctdt.*

reflx$(LIB_SUFFIX): setup_reflx$(LIB_SUFFIX)
	mv setup_reflx$(LIB_SUFFIX) reflx$(LIB_SUFFIX)

clean:
	$(RM) *.o *.cc $(FILES)
