
EXAMPLES = hello movie-lister gps sdr stl-map dsm-sdr dsm-gps on-error robotic-vehicle ext-schema

STDMK_FILE = stdmk

ifeq ($(PLATFORM),Windows_NT)
  STDMK_FILE = stdmk.win
endif

ifeq ($(PLATFORM),VxWorks)
  STDMK_FILE = stdmk.vxWorks
endif

all:
	@if [ ! -d $(POCOCAPSULE_DIR)/install/examples/basic-ioc ]; then \
	  mkdir -p $(POCOCAPSULE_DIR)/install/examples/basic-ioc; \
	fi;
	cp stdmkdir/$(STDMK_FILE) $(POCOCAPSULE_DIR)/install/examples/basic-ioc/stdmk
ifeq ($(PLATFORM),Windows_NT)
	cp makefiles/Makefile.buildWindows_NT $(POCOCAPSULE_DIR)/install/examples/basic-ioc/Makefile
else
	cp makefiles/Makefile.build $(POCOCAPSULE_DIR)/install/examples/basic-ioc/Makefile

endif
	@for ex_dir in $(EXAMPLES); do \
	  $(MAKE) -C $$ex_dir -f makefiles/Makefile.install; \
	done;

