include ../makefiles/Makefile.inc

FILES = \
	README.html\
	MovieFinder.h\
	MovieLister.C\
	MovieLister.h\
	MyMovieFinder.C\
	MyMovieFinder.h\
	setup.xml

REL_DIR = basic-ioc/movie-lister

all:
	$(MKDIR) $(TGT_DIR)
	$(CP) $(FILES) $(TGT_DIR)
	$(call INSTALL_MAIN)
	$(call INSTALL_MK_FILE)

